### ISSUE TITLE
Deployment optimization not possible, file-upload route is a Closure. 

### ISSUE THREAD

**Issue by xewl** [kdion4891/laravel-livewire-forms#19]
### Description
During deployment the `optimize` command failed.
The file-upload endpoint is set up as a Closure.
https://github.com/kdion4891/laravel-livewire-forms/blob/1dd0b4dd11a17abfeee8c921bd9f08ffe90c95b0/routes/web.php#L4-L6

Returning
```bash
  LogicException 

  Unable to prepare route [laravel-livewire-forms/file-upload] for serialization. Uses Closure.
```

### Steps to reproduce
use `php artisan optimize`

**Context**
- laravel-livewire-forms version: ^1.3 (1.3.1)
- Livewire version: ^1.0
- Laravel version: ^7.0

**Comment by papalardo** [comment]
Its easy to resolve. 
Create controller and move the Closure content to this controller. Then send pull request.

**Comment by xewl** [comment]
@papalardo Sure is. Well.. since L8 we can also finally serialize closures, so it shouldn't be a problem at this point.
I sadly passed for the usage of this repository in the end. So, given these 2 factors I'll close this one.
