### ISSUE TITLE
Integration suggestion

### ISSUE THREAD

**Issue by tanthammar** [kdion4891/laravel-livewire-forms#2]
Would be great if you could hook up with Brian Faust in order to use this package, to create the fields needed for his reusable livewire components.
His package does not have any field views, but he has som nice reusable components.

:)
https://github.com/kodekeep/livewired

**Comment by tanthammar** [comment]
posted on that repo:
https://github.com/kodekeep/livewired/issues/1

**Comment by kdion4891** [comment]
Looks interesting. I’ve also been getting into Laravel 7 view components recently as well.
